### ISSUE TITLE
Better icon for marketplace

### ISSUE THREAD

**Issue by dragos** [dragos/dragos-vscode-scala#20]
It would be nice to have a nicer icon for the extension when we get to Marketplace. All Scala plugins are using the Scala logo, so it'd be great to have something a little different. I'm leaving this here, as I'm not at all good at design, maybe someone has some time and desire to fire up Photoshop/Gimp

**Comment by avalonx** [comment]
The Scala logo seems fitting actually considering what it is and provides. I don't think it needs changing unless Scala-lang.org has an issue with it. Another option might be to put the Ensime logo as its most accurately a plugin to Ensime. My vote would be to keep it the way it is, The Scala logo, with The Ensime logo a close second choice.

As for more than one plugin using the Scala logo, I don't have issue with that because the names and particularly the details and description of the plugins are the differentiator that informs their purpose and capabilities anyway.

**Comment by jvican** [comment]
I think this was fixed in https://github.com/dragos/dragos-vscode-scala/pull/28.

**Comment by dragos** [comment]
Yeah, thanks @jvican!
